name: pgadmin
services:
  pgadmin4:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: changeme
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    platform: linux/arm64  # Optional, auto-detected on Apple Silicon
volumes:
  pgadmin_data:

