services:
  postgis:
    image: postgis/postgis:16-3.4
    container_name: postgis
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
      POSTGRES_DB: itinerarius
      POSTGRES_USER: gisuser
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - trailfox_pg_data:/var/lib/postgresql/data
    shm_size: 1g

  martin:
    image: maplibre/martin:latest
    container_name: martin
    restart: unless-stopped
    depends_on:
      - postgis
    ports:
      - "${MARTIN_PORT}:3000"
    command: postgresql://calixtinus:${CALIXTINUS_PASSWORD}@postgis/itinerarius

  postgrest:
    image: postgrest/postgrest:latest
    container_name: postgrest
    restart: unless-stopped
    depends_on:
      - postgis
    ports:
      - "${POSTGREST_PORT}:3000"
    environment:
      PGRST_DB_URI: postgres://calixtinus:${CALIXTINUS_PASSWORD}@postgis:5432/itinerarius
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: calixtinus

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    depends_on:
      - martin
      - postgrest
    ports:
      - "${CADDY_PORT:-8090}:8090"
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro

volumes:
  trailfox_pg_data:
    driver: local
