services:
  postgis:
    image: postgis/postgis:18-3.6
    platform: linux/amd64
    container_name: postgis
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - trailfox_pg_data:/var/lib/postgresql
    shm_size: 2g
    command: >
      -c shared_buffers=2GB 
      -c maintenance_work_mem=2GB 
      -c random_page_cost=1.1
      -c max_wal_size=4GB
      -c checkpoint_timeout=15min

  osm2pgsql:
    image: iboates/osm2pgsql:latest
    profiles:
      - import
    depends_on:
      - postgis
    environment:
      PGPASSWORD: ${DB_ADMIN_PASSWORD}
      PBF_DOWNLOAD_DIR: /tmp
    volumes:
      - ./:/data

  martin:
    image: maplibre/martin:latest
    container_name: martin
    restart: unless-stopped
    depends_on:
      - postgis
    command: postgresql://calixtinus:${APP_PASSWORD}@postgis/itinerarius

  postgrest:
    image: postgrest/postgrest:latest
    container_name: postgrest
    restart: unless-stopped
    depends_on:
      - postgis
    environment:
      PGRST_DB_URI: postgres://calixtinus:${APP_PASSWORD}@postgis:5432/itinerarius
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: calixtinus

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    image: trailfox-caddy:dev
    container_name: caddy
    restart: unless-stopped
    depends_on:
      - martin
      - postgrest
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: unless-stopped
    profiles:
      - tools
    env_file:
      - ./.env
    depends_on:
      - postgis
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - trailfox_pgadmin_data:/var/lib/pgadmin

volumes:
  trailfox_pg_data:
    name: trailfox_pg_data
    driver: local
  trailfox_pgadmin_data:
    name: trailfox_pgadmin_data
    driver: local
