services:

  caddy:
    image: trailfox-caddy:staging
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile:ro
      - /var/www/trailfox.app:/var/www/trailfox.app:ro
      - caddy_data:/data
      - caddy_config:/config

  pgadmin4:
    ports:
      - "127.0.0.1:${PGADMIN_PORT:-5050}:80"

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
