name: Busted tests

on:
  push: {}
  pull_request: {}

jobs:
  busted:
    name: Run busted specs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          # check osm2pgsql --version for reuired Lua version
          sudo apt-get install -y lua-busted

      - name: Run busted
        run: |
          cd server/osm2pgsql
          busted -v
